### ISSUE TITLE
Add plugin to terraform registry

### ISSUE THREAD

**Issue by svenstaro** [gavinbunney/terraform-provider-bitbucketserver#23]
Hey, I think it would be much more convenient to use this plugin if you added it to the new official terraform registry.

**Comment by jesstruck** [comment]
For now I have release it in the registry -> https://registry.terraform.io/providers/jesstruck/bitbucketserver/latest,

The release is merely a tag on what was HEAD of master today.

I'll gladly send a PR on the code changes, but @gavinbunney would still need to setup some GPG keys as well, if he wish to maintain the release in registry, according to the https://www.terraform.io/docs/registry/providers/publishing.html guide.

**Comment by gavinbunney** [comment]
Provider is now available on the Registry 🎉 
https://registry.terraform.io/providers/gavinbunney/bitbucketserver/latest
